main:
  - identifier: projects
    name: 作品
    pageRef: /projects
    weight: 10
  - identifier: field-notes
    name: 现场记录
    pageRef: /field-notes
    weight: 20
  - identifier: now
    name: 此刻
    pageRef: /now
    weight: 30
  - identifier: about
    name: 关于
    pageRef: /page/about
    weight: 40

